#!/bin/sh

USAGE="Usage: `basename $0` [-s <SOCKET>]"
DOCKER_SOCKET=/var/run/docker.sock

while getopts hs: OPT; do
    case "$OPT" in
        h)
            echo $USAGE
            exit 0
            ;;
        s)
            DOCKER_SOCKET=$OPTARG
            ;;
        \?)
            echo $USAGE >&2
            exit 1
            ;;
    esac
done

CTS=$(echo "GET /containers/json?all=1 HTTP/1.0\r\n"|sudo netcat -U $DOCKER_SOCKET|sed '/^HTTP\/1.. 200 OK\r$/,/^\r$/d')
LEN=$(echo $CTS|jq "length")

for I in `seq 0 $(($LEN-1))`
do
    ID=$(echo $CTS|jq ".[$I].Id"|sed -e 's/^"//' -e 's/"$//')
    NAME=$(echo $CTS|jq ".[$I].Names[0]"|sed -e 's/^"\//"/'|sed -e 's/^"//' -e 's/"$//')
    
    CT=$(echo "GET /containers/$ID/json HTTP/1.0\r\n"|sudo netcat -U $DOCKER_SOCKET|sed '/^HTTP\/1.. 200 OK\r$/,/^\r$/d')
    RUNNING=$(echo $CT|jq ".State.Running"|sed -e 's/^"//' -e 's/"$//')
    PID=$(echo $CT|jq ".State.Pid"|sed -e 's/^"//' -e 's/"$//')
    EXITCODE=$(echo $CT|jq ".State.ExitCode"|sed -e 's/^"//' -e 's/"$//')

    echo "- docker.containers.running[$NAME] $RUNNING"
    echo "- docker.containers.pid[$NAME] $PID"
    echo "- docker.containers.exitcode[$NAME] $EXITCODE"

    if [ "$RUNNING" = "true" ]; then
        TOP=$(echo "GET /containers/$ID/top?ps_args=-aux HTTP/1.0\r\n"|sudo netcat -U $DOCKER_SOCKET|sed '/^HTTP\/1.. 200 OK\r$/,/^\r$/d')
        PS=$(echo $TOP|jq ".Processes")
        PS_LEN=$(echo $PS|jq "length")

        for J in `seq 0 $(($PS_LEN-1))`
        do
            P=$(echo $PS|jq ".[$J]")

            PID=$(echo $P|jq ".[1]"|sed -e 's/^"//' -e 's/"$//')
            CPU=$(echo $P|jq ".[2]"|sed -e 's/^"//' -e 's/"$//')
            MEM=$(echo $P|jq ".[3]"|sed -e 's/^"//' -e 's/"$//')
            VSZ=$(echo $P|jq ".[4]"|sed -e 's/^"//' -e 's/"$//')
            RSS=$(echo $P|jq ".[5]"|sed -e 's/^"//' -e 's/"$//')
            COMMAND=$(echo $P|jq ".[10]"|sed -e 's/^"//' -e 's/"$//')

            echo "- docker.top.cpu[$NAME,$PID] $CPU"
            echo "- docker.top.mem[$NAME,$PID] $MEM"
            echo "- docker.top.vsz[$NAME,$PID] $VSZ"
            echo "- docker.top.rss[$NAME,$PID] $RSS"
            echo "- docker.top.command[$NAME,$PID] \"$COMMAND\""
        done
    fi
done
