#!/bin/sh

ZABBIX_SENDER=/usr/bin/zabbix_sender
ZABBIX_CONF=/etc/zabbix/zabbix_agentd.conf

DOCKER_SOCKET=/var/run/docker.sock

CONFIG_FILE=/etc/zabbix/scripts/trapper/docker.conf

[ -r "$CONFIG_FILE" ] && . $CONFIG_FILE

zsendall () {
    echo "$1"|$ZABBIX_SENDER -c $ZABBIX_CONF -i - 2>&1 >/dev/null
}

RET=$(/etc/zabbix/scripts/docker -s $DOCKER_SOCKET)
if [ "$?" -ne "0" ]; then
   exit 1
fi

zsendall "$RET"
